"""Contract tests for HARTOS integrations.social.chat_messages (U1-U3).

Uses an in-memory SQLite + monkeypatched ``get_db`` so we can exercise
persist / pull_since / publish_new without a real Flask app or the
crossbar HTTP bridge.  The ConversationEntry table is bootstrapped via
``Base.metadata.create_all`` on each test.
"""
from __future__ import annotations

import importlib

import pytest

# HARTOS may not be importable in all environments (cloud CI without
# the pip dep).  Skip the whole module rather than ERROR at collection.
# Use ``integrations.social.models`` (the canonical proxy) not
# ``_models_local`` directly so we pick up whichever backing the host
# has — sql.models (Hevolve_Database pip) or _models_local fallback.
try:
    from integrations.social import chat_messages as cm
    from integrations.social.models import Base, ConversationEntry
    # User class name differs: SocialUser (canonical) vs User (fallback).
    try:
        from integrations.social.models import SocialUser as User  # type: ignore
    except ImportError:
        from integrations.social.models import User  # type: ignore
    _HARTOS_AVAILABLE = True
except Exception:  # noqa: BLE001
    _HARTOS_AVAILABLE = False

pytestmark = pytest.mark.skipif(
    not _HARTOS_AVAILABLE,
    reason="HARTOS social models not importable (pip not installed)"
)


@pytest.fixture
def in_memory_db(monkeypatch):
    """In-process SQLite backing + monkeypatched get_db that yields new
    sessions.  Each test starts with a fresh schema."""
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker
    from sqlalchemy.pool import StaticPool

    # StaticPool + check_same_thread=False keeps the single in-memory
    # connection alive across ALL sessions, so the background thread
    # in persist_and_publish_async sees the seeded user and the
    # test-thread sees its async writes.  Without this, each Session()
    # opens a fresh :memory: DB and the data disappears.
    engine = create_engine(
        'sqlite://',
        future=True,
        connect_args={'check_same_thread': False},
        poolclass=StaticPool,
    )
    # Only create the tables chat_messages actually uses — User (FK) +
    # ConversationEntry.  Creating every table pulls relationships that
    # may not map cleanly on SQLite.
    User.__table__.create(engine, checkfirst=True)
    ConversationEntry.__table__.create(engine, checkfirst=True)

    Session = sessionmaker(bind=engine, autoflush=True, autocommit=False)
    session = Session()
    # Seed a user so FK constraints pass.
    user = User(id='u1', username='u1', user_type='human')
    session.add(user)
    session.commit()

    def fake_get_db():
        return Session()

    # Reload chat_messages so its lazy _MODELS_CACHE picks up fake.
    importlib.reload(cm)
    monkeypatch.setattr(
        'integrations.social.models.get_db', fake_get_db, raising=False,
    )
    # The module caches on first _models() call; prime it explicitly.
    cm._MODELS_CACHE.clear()

    # Stub out the message bus so publish_new never tries to reach
    # crossbar / peer_link.  publish_new must remain callable but a
    # no-op in unit-test mode.
    class _StubBus:
        def publish(self, topic, data=None, **kw):
            return None
    monkeypatch.setattr(
        'core.peer_link.message_bus.get_message_bus',
        lambda: _StubBus(),
        raising=False,
    )
    yield session
    session.close()


def test_persist_minimal_valid_row(in_memory_db):
    row = cm.persist('u1', 'user', 'hello world')
    assert row is not None
    assert row['user_id'] == 'u1'
    assert row['role'] == 'user'
    assert row['content'] == 'hello world'
    assert row['msg_id']  # autogenerated
    assert row['id'] >= 1  # autoincrement seq


def test_persist_rejects_bad_role(in_memory_db):
    assert cm.persist('u1', 'admin', 'hi') is None  # not in allowed set


def test_persist_rejects_empty_content(in_memory_db):
    assert cm.persist('u1', 'user', '') is None
    assert cm.persist('u1', 'user', None) is None  # type: ignore[arg-type]


def test_persist_dedup_on_msg_id(in_memory_db):
    first = cm.persist('u1', 'user', 'duplicate', msg_id='fixed-id-16')
    again = cm.persist('u1', 'user', 'different content', msg_id='fixed-id-16')
    assert first is not None and again is not None
    assert first['id'] == again['id']  # same row returned
    # First-write-wins on content for the same msg_id.
    assert again['content'] == 'duplicate'


def test_persist_cross_user_collision_refused(in_memory_db):
    """A msg_id collision across two user_ids must NOT leak the other
    user's row.  Astronomically rare with 64 bits of entropy, but
    defense in depth verified here."""
    from sqlalchemy.orm import sessionmaker
    session_cls = sessionmaker(bind=in_memory_db.get_bind())
    with session_cls() as s:
        s.add(User(id='u2', username='u2', user_type='human'))
        s.commit()
    # u1 claims 'shared-id'.
    a = cm.persist('u1', 'user', 'alpha', msg_id='shared-id')
    assert a is not None
    # u2 tries to reuse.  Service MUST refuse rather than return u1's row.
    b = cm.persist('u2', 'user', 'beta', msg_id='shared-id')
    assert b is None


def test_pull_since_returns_only_rows_newer_than_cursor(in_memory_db):
    a = cm.persist('u1', 'user', 'first')
    b = cm.persist('u1', 'assistant', 'second')
    c = cm.persist('u1', 'user', 'third')
    assert a and b and c

    # Cursor = 0 returns all.
    got = cm.pull_since('u1', 0)
    ids = [r['id'] for r in got]
    assert ids == sorted(ids)  # ascending
    assert len(got) == 3

    # Cursor at a['id'] returns only b + c.
    got = cm.pull_since('u1', a['id'])
    ids = [r['id'] for r in got]
    assert a['id'] not in ids
    assert b['id'] in ids
    assert c['id'] in ids


def test_pull_since_respects_user_scope(in_memory_db):
    from sqlalchemy.orm import sessionmaker
    session_cls = sessionmaker(bind=in_memory_db.get_bind())
    with session_cls() as s:
        s.add(User(id='u2', username='u2', user_type='human'))
        s.commit()
    cm.persist('u1', 'user', 'u1-secret')
    cm.persist('u2', 'user', 'u2-secret')
    got_u1 = cm.pull_since('u1', 0)
    got_u2 = cm.pull_since('u2', 0)
    assert all(r['user_id'] == 'u1' for r in got_u1)
    assert all(r['user_id'] == 'u2' for r in got_u2)


def test_pull_since_fills_legacy_msg_id(in_memory_db):
    """Rows inserted directly without msg_id (legacy pre-v38) must get
    a synthetic ``legacy-<id>`` key on read so clients can still dedup."""
    from sqlalchemy.orm import sessionmaker
    session_cls = sessionmaker(bind=in_memory_db.get_bind())
    with session_cls() as s:
        s.add(ConversationEntry(
            user_id='u1', channel_type='chat', role='user',
            content='legacy', msg_id=None,
        ))
        s.commit()
    got = cm.pull_since('u1', 0)
    assert any(r['msg_id'] == f"legacy-{r['id']}" for r in got)


def test_pull_since_limit_clamped(in_memory_db):
    for i in range(30):
        cm.persist('u1', 'user', f'msg {i}')
    got = cm.pull_since('u1', 0, limit=5)
    assert len(got) == 5
    got = cm.pull_since('u1', 0, limit=10000)  # attempt to exceed cap
    # row_cap is clamped to CHAT_CURSOR_PULL_MAX_ROWS (500).
    assert len(got) == 30


def test_pull_since_filters_channel_and_agent(in_memory_db):
    cm.persist('u1', 'user', 'a', channel_type='chat')
    cm.persist('u1', 'user', 'b', channel_type='slack')
    cm.persist('u1', 'user', 'c', channel_type='chat', agent_id='agent-x')
    chat_only = cm.pull_since('u1', 0, channel_type='chat')
    assert all(r['channel_type'] == 'chat' for r in chat_only)
    agent_only = cm.pull_since('u1', 0, agent_id='agent-x')
    assert len(agent_only) == 1
    assert agent_only[0]['agent_id'] == 'agent-x'


def test_generate_msg_id_is_hex_and_time_prefixed():
    mid = cm._generate_msg_id()
    assert len(mid) == 16
    assert all(c in '0123456789abcdef' for c in mid)
    # Two successive ids: the ms prefix (first 12 hex) must be non-
    # decreasing — rare ms wrap would break this but extremely unlikely
    # in a single test.
    mid2 = cm._generate_msg_id()
    assert mid[:12] <= mid2[:12]


def test_persist_and_publish_async_does_not_block(in_memory_db):
    """Executor submit returns immediately — the chat hot path must
    not wait on DB + WAMP.  We only verify the call doesn't raise and
    the row eventually appears via pull_since."""
    import time as _t
    t0 = _t.perf_counter()
    cm.persist_and_publish_async('u1', 'user', 'async hot path')
    elapsed = _t.perf_counter() - t0
    assert elapsed < 0.1, f"submit blocked for {elapsed}s"
    # Wait up to 2s for the worker to flush the row.
    for _ in range(20):
        rows = cm.pull_since('u1', 0)
        if any(r['content'] == 'async hot path' for r in rows):
            break
        _t.sleep(0.1)
    else:
        pytest.fail("async persist did not land within 2s")
